ogbg-molhiv:
  learning_rate: 0.001
  epochs: 200
  dropout: 0.3
  num_layers: 4
  batch_size: 256
  hidden_size: 64
  weight_decay: 0.0001
PROTEINS:
  learning_rate: 0.001
  epochs: 100
  dropout: 0.3
  num_layers: 3
  batch_size: 64
  hidden_size: 64
  weight_decay: 0.0001

NCI1:
  learning_rate: 0.0005
  epochs: 500
  dropout: 0.3
  num_layers: 3
  batch_size: 64
  hidden_size: 64
  weight_decay: 0.001

NCI109:
  learning_rate: 0.0005
  epochs: 100
  dropout: 0.3
  num_layers: 4
  batch_size: 64
  hidden_size: 64
  weight_decay: 0.005


DD:
  learning_rate: 0.005
  epochs: 300
  dropout: 0.5
  num_layers: 3
  batch_size: 128
  hidden_size: 128
  weight_decay: 0.00

COLLAB:
  learning_rate: 0.001
  epochs: 500
  dropout: 0.5
  num_layers: 4
  batch_size: 64
  hidden_size: 64
  weight_decay: 0.005


IMDB-BINARY:
  learning_rate: 0.001
  epochs: 100
  dropout: 0
  num_layers: 4
  batch_size: 128
  hidden_size: 64
  weight_decay: 0.0005

REDDIT-MULTI-5K:
  learning_rate: 0.0001
  epochs: 100
  dropout: 0
  num_layers: 3
  batch_size: 128
  hidden_size: 32
  weight_decay: 0.01

reddit_threads:
  learning_rate: 0.01
  epochs: 75
  dropout: 0
  num_layers: 3
  batch_size: 128
  hidden_size: 32
  weight_decay: 0.001


IMDB-MULTI:
  learning_rate: 0.0001
  epochs: 100
  dropout: 0.3
  num_layers: 3
  batch_size: 128
  hidden_size: 32
  weight_decay: 0

Letter-high:
  learning_rate: 0.01
  epochs: 100
  dropout: 0
  num_layers: 3
  batch_size: 128
  hidden_size: 32
  weight_decay: 0.01

COIL-RAG:
  learning_rate: 0.01
  epochs: 100
  dropout: 0.3
  num_layers: 3
  batch_size: 32
  hidden_size: 32
  weight_decay: 0.01